language: node_js
branches:
  only:
  - master
node_js:
  - "12"
sudo: false
install:
  - npm install
  - npm audit
  - npm run lint
script:
  - cat README.md
  - echo "harry" > README.md
  - cat README.md